# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 20:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chief', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaordSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_back_url', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'Новый'), (1, 'Принят'), (2, 'Отменён'), (3, 'Отправлен'), (4, 'Ждёт оплаты'), (5, 'Оплачен'), (6, 'Перевод'), (7, 'Возврат'), (8, 'Дубликат'), (9, 'Ошибка')])),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chief.Project')),
            ],
        ),
        migrations.CreateModel(
            name='OrderField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=True, verbose_name='Включено')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('vtype', models.IntegerField(choices=[(0, 'Строка'), (1, 'Число'), (2, 'Текст'), (3, 'Флажок'), (4, 'Время'), (5, 'Email'), (6, 'Телефон')], verbose_name='Тип')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('pattern', models.CharField(default='.+', max_length=256, verbose_name='Шаблон')),
                ('error_msg', models.CharField(default='Одно из полей заполненно неправильно.', max_length=256, verbose_name='Сообщение об ошибке')),
                ('can_worker_edit', models.BooleanField(default=True, verbose_name='Оператор может редактировать')),
                ('can_webms_view', models.BooleanField(default=True, verbose_name='Web-мастер может просматривать')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chief.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orderfield',
            unique_together=set([('project', 'name')]),
        ),
    ]
