# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 15:58
from __future__ import unicode_literals
from django.db import migrations
from django.contrib.auth.models import User
from metaord import settings
from metaord.models import Order, Project, OrderField
from metaord.utils.auth import Groups
from metaord.utils.models import create_default_order_fields
from webms.models import Webms
from chief.models import WebmsInvite


def add_group_permissions(apps, schema_editor):
    Groups.get_or_create_chief()
    Groups.get_or_create_worker()
    Groups.get_or_create_webms()

def create_test_users_and_data(apps, schema_editor):
    t1, created = User.objects.get_or_create(username="t1", email='c@b.ru', first_name='t1')
    t1.set_password('123')
    t1.save()
    t1.groups.add(Groups.get_or_create_worker())

    t2, created = User.objects.get_or_create(username="t2", email='c@b.ru', first_name='t2')
    t2.set_password('123')
    t2.save()
    t2.groups.add(Groups.get_or_create_chief())

    t3, created = User.objects.get_or_create(username="t3", email='c@b.ru', first_name='t3')
    t3.set_password('123')
    t3.save()
    t3.groups.add(Groups.get_or_create_webms())
    wm, created = Webms.objects.get_or_create(user=t3)

    t4, created = User.objects.get_or_create(username="t4", email='c@b.ru', first_name='t4')
    t4.set_password('123')
    t4.is_staff = True
    t4.is_superuser = True
    t4.save()

    proj, created = Project.objects.get_or_create(name='Тестовый проект')
    create_default_order_fields(proj)

    # Order.objects.get_or_create(project=proj, status=2, fields={fio.pk: "Raushan Ahmedov", em.pk: "a@b.ru", ph.pk: "8732431"})
    # Order.objects.get_or_create(project=proj, status=6, fields={fio.pk: "Георгий Пупкин", em.pk: "c@d.ru", ph.pk: "567443"})
    invite = WebmsInvite.objects.get_or_create(project=proj, webms=wm)

class Migration(migrations.Migration):

    dependencies = [
        ('metaord', '0001_initial'),
        ('webms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
    if settings.DEBUG:
            operations.append(migrations.RunPython(create_test_users_and_data))
