# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaord', '0002_order_is_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-post_date']},
        ),
    ]
