# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaord', '0003_auto_20170501_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfield',
            name='is_display_on_table',
            field=models.BooleanField(default=True, verbose_name='Отображать на странице заказов'),
        ),
    ]
