# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('pb_order_create', models.TextField(blank=True, verbose_name='Тело post-back сообщения при создании заказа в формате JSON')),
                ('pb_order_upd_status', models.TextField(blank=True, verbose_name='Тело post-back сообщения при обновлении статуса заказа в формате JSON')),
                ('pb_url', models.URLField(blank=True, verbose_name='Post-back URL')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chief.Chief')),
            ],
        ),
        migrations.CreateModel(
            name='WebmsInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Новый'), (2, 'Принят'), (3, 'Отклонён')], default=1, verbose_name='Статус приглашения')),
                ('orders_amt', models.IntegerField(default=0, verbose_name='Заказов от приглашения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chief.Project', verbose_name='Проект')),
                ('webms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webms.Webms', verbose_name='Web-мастер')),
            ],
        ),
    ]
